networks:
  arnelify-network:
    name: arnelify-network
    driver: bridge
    
services:
  python_amd64:
    platform: linux/amd64
    container_name: python_amd64
    build:
      context: .
      dockerfile: python.dockerfile
    volumes:
      - ./:/var/www/python
    restart: unless-stopped
    networks:
      - arnelify-network
    tty: true